//
//  Generated file. Do not edit.
//  This file is auto-generated by `flutter pub get`. Do not modify.
//
import FlutterMacOS
import Foundation
// This file is a stub — the real one is generated by `flutter pub get`.
